---
- name: Install Prerequisites
  hosts: local
  tasks:
    - import_role:
        name: install_prereqs

- name: Install ArgoCD
  hosts: local
  tasks:
    - import_role:
        name: install_argocd
...
