---
- name: Get latest ArgoCD CLI release
  github_release:
    user: argoproj
    repo: argo-cd
    action: latest_release
  register: argocd_release

- name: Install ArgoCD CLI binary
  get_url:
    url: "https://github.com/argoproj/argo-cd/releases/download/{{ argocd_release.tag }}/argocd-linux-amd64"
    dest: "{{ bin_dir }}/argocd"
    mode: "+x"
...
