---
- name: Get latest kubectl CLI release
  github_release:
    user: kubernetes
    repo: kubernetes
    action: latest_release
  register: k8s_release

- name: Get kubectl binary
  unarchive:
    src: "https://dl.k8s.io/{{ k8s_release.tag }}/kubernetes-client-linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Install kubectl binary
  copy:
    src: /tmp/kubernetes/client/bin/kubectl
    dest: "{{ bin_dir }}/kubectl"
    mode: "+x"
...
