---
# scope is namespace or cluster
scope: namespace

  # state is present or absent
state: present

# Replace with the path to your kubeconfig
kubeconfig: "/home/{{ ansible_user_id }}/.minishift/machines/minishift_kubeconfig"
...
