---
# scope is namespace or cluster
scope: namespace

# state is present or absent
state: present

# Replace with the path to your kubeconfig
# NOTE: Must be cluster-admin to install CRDs and cluster scoped operator!
kubeconfig: "/home/{{ ansible_user_id }}/.minishift/machines/minishift_kubeconfig"

# The namespace to install the operator into.
# Used for both namespace and cluster scoped installations.
namespace: argocd
...
