---
- name: Get default ArgoCD operator.yaml
  set_fact:
    operator_json: "{{ lookup('file', \"{{ role_path }}/files/argocd-operator/deploy/operator.yaml\") | from_yaml }}"
  when: scope == 'cluster'

- name: Set operator_image
  set_fact:
    operator_image: "{{ operator_json.spec.template.spec.containers[0].image }}"
  when: scope == 'cluster'

- name: Populate cluster-operator.yaml
  template:
    src: "{{ role_path }}/templates/cluster-scoped-operator.yaml.j2"
    dest: "{{ role_path }}/files/argocd-operator/deploy/operator.yaml"
    # Need to force since we're replacing the default
    force: yes
  when: scope == 'cluster'
...
