---
- name: Get latest ArgoCD CLI release
  github_release:
    user: argoproj
    repo: argo-cd
    action: latest_release
  register: argocd_release

- name: Download install manifest
  get_url:
    url: "https://raw.githubusercontent.com/argoproj/argo-cd/{{ argocd_release.tag }}/manifests/install.yaml"
    dest: "{{ role_path }}/files/install.yaml"

- name: Namespace argocd is present
  k8s:
    name: argocd
    kind: Namespace
    api_version: v1
    state: present
    kubeconfig: "{{ kubeconfig }}"

- name: Install argocd
  k8s:
    namespace: argocd
    src: "{{ role_path }}/files/install.yaml"
    state: present
    kubeconfig: "{{ kubeconfig }}"

- name: Expose server service
...
