---
- name: Get latest ArgoCD CLI release
  github_release:
    user: argoproj-labs
    repo: argocd-operator
    action: latest_release
  register: operator_release

- name: Get ArgoCD Operator code
  git:
    repo: https://github.com/argoproj-labs/argocd-operator.git
    dest: "{{ role_path }}/files"
    version: "{{ operator_release.tag }}"

- name: Namespace argocd is present
  k8s:
    name: argocd
    kind: Namespace
    api_version: v1
    state: present
    kubeconfig: "{{ kubeconfig }}"

- name: Install ArgoCD Operator
  k8s:
    namespace: argocd
    src: "{{ role_path }}/files/deploy/{{ item }}"
    state: present
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - service_account.yaml
    - role.yaml
    - role_binding.yaml
    - argo-cd/
    - crds/
    - operator.yaml
...
