---
- name: Get latest ArgoCD CLI release
  github_release:
    user: argoproj-labs
    repo: argocd-operator
    action: latest_release
  register: operator_release

- name: Get ArgoCD Operator code from GitHub
  git:
    repo: https://github.com/argoproj-labs/argocd-operator.git
    dest: "{{ role_path }}/files/argocd-operator"
    version: "{{ operator_release.tag }}"

- name: Namespace argocd is {{ state }}
  k8s:
    name: argocd
    kind: Namespace
    api_version: v1
    state: "{{ state }}"
    kubeconfig: "{{ kubeconfig }}"

- name: "{{ 'Create' if state == present else 'Remove' }} cluster-admin Rolebinding"
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        labels:
          app.kubernetes.io/component: application-controller
          app.kubernetes.io/name: argocd-application-controller
          app.kubernetes.io/part-of: argocd
        name: argocd-application-controller
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: argocd-application-controller
        namespace: argocd
  when: scope == cluster
...
